mytestkey=This value is from LOCAL properties file


paypal.clientId=${PAYPAL_CLIENT_ID}
paypal.clientSecretKey=${PAYPAL_CLIENT_SECRET_KEY}

paypal.oauthURL = https://api-m.sandbox.paypal.com/v1/oauth2/token
paypal.createOrderURL = https://api-m.sandbox.paypal.com/v2/checkout/orders
paypal.captureOrderURL = https://api-m.sandbox.paypal.com/v2/checkout/orders/{orderId}/capture