mytestkey=This value is from LOCAL properties file

# ========== Eureka Server Configuration ==========

# Do not register this Eureka Server itself as a client inside Eureka
eureka.client.register-with-eureka=false

# Do not fetch service registry details from Eureka because this application itself is the registry server
eureka.client.fetch-registry=false


# Start immediately without waiting for peer Eureka servers to sync (useful for single-server local/dev setup)
eureka.server.wait-time-in-ms-when-sync-empty=0


# Remove service instance if heartbeat is not received within 10 seconds
# (default is 90 seconds)
eureka.instance.lease-expiration-duration-in-seconds=10


# Eureka checks every 5 seconds for expired/down service instances and removes them
# (default is 60 seconds)
eureka.server.eviction-interval-timer-in-ms=5000


# Disable self-preservation mode so dead instances are removed quickly
# Recommended only for Development/Testing environments
eureka.server.enable-self-preservation=false
